In [4]:
import numpy as np

# Crear matrices
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Operaciones básicas
suma = A + B            # Suma de matrices
resta = A - B           # Resta de matrices
producto = np.dot(A, B) # Producto matricial
transpuesta = A.T       # Transpuesta de A
inversa = np.linalg.inv(A)  # Inversa de A (si es invertible)
autovalores, autovectores = np.linalg.eig(A)

# Mostrar resultados
print("Suma de matrices:\n", suma)
print("Producto de matrices:\n", producto)
print("Transpuesta de matrices:\n", transpuesta)
print("Inbersa de matrices:\n", inversa)
print("Autovalores:", autovalores)
print("Autovectores:\n", autovectores)

Suma de matrices:
 [[ 3  3  2]
 [ 1  4  8]
 [ 5  9 11]]
Producto de matrices:
 [[-1  1  3]
 [ 7  5  3]
 [16 17 18]]
Transpuesta de matrices:
 [[ 2 -3 -2]
 [ 1 -1  1]
 [-1  2  2]]
Inbersa de matrices:
 [[ 4.  3. -1.]
 [-2. -2.  1.]
 [ 5.  4. -1.]]
Autovalores: [ 3.21431974  0.46081113 -0.67513087]
Autovectores:
 [[-0.22113623  0.58085736  0.46692616]
 [ 0.54213889 -0.08443477 -0.65511222]
 [ 0.81066898  0.80961441  0.59397638]]


In [ ]:
from sympy import symbols, simplify, expand
from sympy import diff
from sympy import integrate
from sympy import Eq, solve
from sympy import limit
from sympy import pretty, latex

# Definir variables simbólicas
x, y, z = symbols('x y z')
# Crear una expresión simbólica
expr = (x**2 + 2*x + 1)**2
# Operaciones básicas
expand_expr = expand(expr)  # Expandir la expresión
simplify_expr = simplify(expr)  # Simplificar la expresión (si es necesario)
# Calcular la derivada de f respecto a x
df_dx = diff(expr, x)
# Segunda derivada de f respecto a x
d2f_dx2 = diff(expr, x, 2)
# Calcular la integral indefinida de f respecto a x
integral_indef = integrate(expr, x)
# Calcular la integral definida de f en el intervalo [0, 2]
integral_def = integrate(expr, (x, 0, 2))
# Resolver la ecuación
soluciones = solve(expr, x)
# Calcular el límite de g cuando x tiende a 1
limite = limit(expr, x, 1)

# Mostrar la expresión en formato LaTeX
print("Expresión en formato LaTeX:")
print(latex(expr))
print("Derivada de f respecto a x:", df_dx)
print("Segunda derivada de f respecto a x:", d2f_dx2)
print("Función original:", expr)
print("Expresión expandida:", expand_expr)
print("Expresión simplificada:", simplify_expr)
print("Integral indefinida de f:", integral_indef)
print("Integral definida de f en [0, 2]:", integral_def)
print("Soluciones de la ecuación:", soluciones)
print("Límite de g cuando x -> 1:", limite)


Derivada de f respecto a x: (4*x + 4)*(x**2 + 2*x + 1)
Segunda derivada de f respecto a x: 4*(x**2 + 2*x + 2*(x + 1)**2 + 1)
Función original: (x**2 + 2*x + 1)**2
Expresión expandida: x**4 + 4*x**3 + 6*x**2 + 4*x + 1
Expresión simplificada: (x**2 + 2*x + 1)**2
Integral indefinida de f: x**5/5 + x**4 + 2*x**3 + 2*x**2 + x
Integral definida de f en [0, 2]: 242/5
Soluciones de la ecuación: [-1]
Límite de g cuando x -> 1: 16
Expresión en formato LaTeX:
\left(x^{2} + 2 x + 1\right)^{2}


In [14]:
import numpy as np

# Crear matrices
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Crear un vector
v = np.array([1, 2, 3])

# Operaciones básicas
suma = A + B                # Suma de matrices
resta = A - B               # Resta de matrices
producto = np.dot(A, B)     # Producto matricial
producto_elemento = A * B   # Producto elemento a elemento
transpuesta = A.T           # Transpuesta de A
inversa = np.linalg.inv(A)  # Inversa de A (si es invertible)
determinante = np.linalg.det(A)  # Determinante de A
rango = np.linalg.matrix_rank(A)  # Rango de la matriz A

# Solución de sistemas de ecuaciones Ax = b
b = np.array([1, 2, 3])  # Vector de términos independientes
x = np.linalg.solve(A, b)  # Resolver el sistema Ax = b

# Normas
norma_vector = np.linalg.norm(v)  # Norma del vector v
norma_matriz = np.linalg.norm(A)  # Norma de la matriz A

# Autovalores y autovectores
autovalores, autovectores = np.linalg.eig(A)  # Autovalores y autovectores de A

# Descomposición en valores singulares (SVD)
U, S, Vt = np.linalg.svd(A)  # Descomposición SVD de A

# Descomposición LU
from scipy.linalg import lu
P, L, U = lu(A)  # Descomposición LU de A

# Producto cruzado y escalar de vectores
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
producto_cruzado = np.cross(v1, v2)  # Producto cruzado
producto_escalar = np.dot(v1, v2)    # Producto escalar

# Proyección de un vector sobre otro
proyeccion = np.dot(v1, v2) / np.linalg.norm(v2)**2 * v2

# Valores mínimos y máximos de una matriz
valor_min = np.min(A)  # Valor mínimo
valor_max = np.max(A)  # Valor máximo

# Diagonal y trazas
diagonal = np.diag(A)             # Diagonal de A
traza = np.trace(A)               # Traza de A (suma de elementos de la diagonal)

# Exponencial de una matriz
from scipy.linalg import expm
exponencial_matriz = expm(A)  # Exponencial de la matriz A


print("Matriz A:\n", A)
print("Matriz B:\n", B)
print("Suma de matrices:\n", suma)
print("Producto matricial:\n", producto)
print("Transpuesta de A:\n", transpuesta)
print("Inversa de A:\n", inversa)
print("Determinante de A:", determinante)
print("Rango de A:", rango)
print("Solución del sistema Ax = b:", x)
print("Autovalores de A:", autovalores)
print("Autovectores de A:\n", autovectores)



Matriz A:
 [[ 2  1 -1]
 [-3 -1  2]
 [-2  1  2]]
Matriz B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Suma de matrices:
 [[ 3  3  2]
 [ 1  4  8]
 [ 5  9 11]]
Producto matricial:
 [[-1  1  3]
 [ 7  5  3]
 [16 17 18]]
Transpuesta de A:
 [[ 2 -3 -2]
 [ 1 -1  1]
 [-1  2  2]]
Inversa de A:
 [[ 4.  3. -1.]
 [-2. -2.  1.]
 [ 5.  4. -1.]]
Determinante de A: -1.0
Rango de A: 3
Solución del sistema Ax = b: [ 7. -3. 10.]
Autovalores de A: [ 3.21431974  0.46081113 -0.67513087]
Autovectores de A:
 [[-0.22113623  0.58085736  0.46692616]
 [ 0.54213889 -0.08443477 -0.65511222]
 [ 0.81066898  0.80961441  0.59397638]]
